// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjeiZXQmfYdfkYNibrbbhMAxdSX4jgKDY',
    appId: '1:178772363203:web:684f41ec74c77cdf6f9f76',
    messagingSenderId: '178772363203',
    projectId: 'buurhuurproject',
    authDomain: 'buurhuurproject.firebaseapp.com',
    storageBucket: 'buurhuurproject.firebasestorage.app',
    measurementId: 'G-MSB9WCRCCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrayLUux5fhT5L6T9AGWJJYVB-N0vWcg',
    appId: '1:178772363203:android:41aa39c0ac6911c16f9f76',
    messagingSenderId: '178772363203',
    projectId: 'buurhuurproject',
    storageBucket: 'buurhuurproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0eS9LYz7LtcLQNGmEKHv1BTuySX6ulK4',
    appId: '1:178772363203:ios:eda1a6472d07bab16f9f76',
    messagingSenderId: '178772363203',
    projectId: 'buurhuurproject',
    storageBucket: 'buurhuurproject.firebasestorage.app',
    iosBundleId: 'com.example.deelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0eS9LYz7LtcLQNGmEKHv1BTuySX6ulK4',
    appId: '1:178772363203:ios:eda1a6472d07bab16f9f76',
    messagingSenderId: '178772363203',
    projectId: 'buurhuurproject',
    storageBucket: 'buurhuurproject.firebasestorage.app',
    iosBundleId: 'com.example.deelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjeiZXQmfYdfkYNibrbbhMAxdSX4jgKDY',
    appId: '1:178772363203:web:e43455f1a6ce74c26f9f76',
    messagingSenderId: '178772363203',
    projectId: 'buurhuurproject',
    authDomain: 'buurhuurproject.firebaseapp.com',
    storageBucket: 'buurhuurproject.firebasestorage.app',
    measurementId: 'G-ZCBQZZLDR3',
  );
}
